from __future__ import annotations

import argparse
import csv
from pathlib import Path

from main import (
	QUESTION_KEYS,
	build_client,
	get_error_path,
	get_output_path,
	load_model_config,
	parse_index_selection,
	write_results,
)


def parse_args() -> argparse.Namespace:
	parser = argparse.ArgumentParser(
		description=(
			"Check and fix CSV run counts for one index or a range, "
			"for example: 58 --check_times=500"
		),
	)
	parser.add_argument(
		"index",
		type=str,
		nargs="?",
		default="",
		help='Model index or inclusive range, e.g. 58 or "[55, 58]".',
	)
	parser.add_argument(
		"--models",
		type=str,
		default="",
		help='Model index or inclusive range, e.g. 58 or "[55, 58]".',
	)
	parser.add_argument(
		"--check_times",
		type=int,
		default=200,
		help="Target number of rows each selected model should have.",
	)
	parser.add_argument(
		"--double_check",
		action="store_true",
		help=(
			"Re-check after each backfill and continue until target row count is met."
		),
	)
	parser.add_argument(
		"--job_id",
		type=str,
		default="",
		help=(
			"Optional output file suffix (same behavior as main.py --job_id). "
			"Use this when checking files generated by a specific job."
		),
	)
	args = parser.parse_args()
	if not args.index and not args.models:
		parser.error('Provide index (positional) or "--models".')
	if args.index and args.models:
		parser.error('Use either positional index or "--models", not both.')
	return args


def count_rows(csv_path: Path) -> int:
	if not csv_path.exists() or csv_path.stat().st_size == 0:
		return 0

	with csv_path.open("r", newline="", encoding="utf-8") as handle:
		reader = csv.DictReader(handle)
		return sum(1 for _ in reader)


def truncate_to_rows(csv_path: Path, keep_rows: int) -> None:
	fieldnames = ["model"] + QUESTION_KEYS

	if keep_rows < 0:
		raise ValueError("keep_rows must be >= 0")

	rows: list[dict[str, str]] = []
	if csv_path.exists() and csv_path.stat().st_size > 0:
		with csv_path.open("r", newline="", encoding="utf-8") as handle:
			reader = csv.DictReader(handle)
			for row in reader:
				rows.append(row)

	trimmed_rows = rows[:keep_rows]

	csv_path.parent.mkdir(parents=True, exist_ok=True)
	with csv_path.open("w", newline="", encoding="utf-8") as handle:
		writer = csv.DictWriter(handle, fieldnames=fieldnames)
		writer.writeheader()
		writer.writerows(trimmed_rows)


def sync_model_runs(
	index: int,
	run_time: int,
	double_check: bool = False,
	job_id: str = "",
) -> None:
	model_config = load_model_config(index)
	output_path = get_output_path(model_config.model_name, job_id)
	error_path = get_error_path(model_config.model_name)

	client = None
	max_rounds = max(run_time * 3, 10)
	last_count = -1

	for round_num in range(1, max_rounds + 1):
		existing = count_rows(output_path)
		delta = run_time - existing

		print(
			f"row={model_config.index}, model={model_config.model_name}, "
			f"target={run_time}, existing={existing}, round={round_num}"
		)

		if delta == 0:
			print("  already matched, no action")
			return

		if delta < 0:
			over_by = -delta
			print(f"  exceeds by {over_by} rows, truncating...")
			truncate_to_rows(output_path, run_time)
			final_count = count_rows(output_path)
			print(f"  truncate done, now={final_count}")
			if final_count == run_time:
				return
			continue

		print(f"  missing {delta} rows, backfilling...")
		if client is None:
			client = build_client(model_config.family)

		success_count, failure_count = write_results(
			client=client,
			model_config=model_config,
			run_time=delta,
			output_path=output_path,
			error_path=error_path,
		)
		final_count = count_rows(output_path)
		print(
			f"  backfill done: success={success_count}, failure={failure_count}, "
			f"now={final_count}"
		)

		if not double_check:
			return

		if final_count == run_time:
			return

		if final_count == last_count:
			raise RuntimeError(
				"double-check mode made no progress after backfill; "
				"please inspect error logs and retry."
			)

		last_count = final_count

	raise RuntimeError(
		"double-check mode reached max rounds without hitting target rows; "
		"please inspect error logs."
	)


def main() -> None:
	args = parse_args()
	if args.check_times < 1:
		raise ValueError("check_times must be >= 1")

	raw_index_selection = args.index or args.models
	selected_indices = parse_index_selection(raw_index_selection)

	print(
		f"index={raw_index_selection}, check_times={args.check_times}, "
		f"rows={selected_indices}, double_check={args.double_check}, job_id={args.job_id}"
	)
	for index in selected_indices:
		sync_model_runs(
			index=index,
			run_time=args.check_times,
			double_check=args.double_check,
			job_id=args.job_id,
		)


if __name__ == "__main__":
	main()

	# python check.py "[56, 58]" --check_times=500
	# python check.py 55 --check_times=500
	# python check.py --models=55 --check_times=500 --double_check
	# nohup python -u check.py "[55,58]" --check_times=500 --double_check --job_id="$SLURM_ARRAY_TASK_ID" 2>&1 | tee output.log
